sudo: true
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        - COMPILER_FLAGS="-DCMAKE_CXX_FLAGS=-Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic"
        - EXTRA_FLAGS=""
        - AFTER_BUILD=""

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
        - COMPILER_FLAGS="-DCMAKE_CXX_FLAGS=-Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic"
        - EXTRA_FLAGS=""
        - AFTER_BUILD=""

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - clang-tidy-8
            - clang-format-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
        - EXTRA_FLAGS="-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
        - AFTER_BUILD="clang-tidy-8 -p build/ *.cpp deviceconfigs/*.cpp ui/*.cpp utility/*.cpp command/*.cpp *.h deviceconfigs/*.h ui/*.h utility/*.h command/*.h *.hpp deviceconfigs/*.hpp ui/*.h utility/*.hpp command/*.hpp"

before_install:
  # Qt
  - sudo add-apt-repository ppa:beineri/opt-qt-5.11.0-xenial -y
  - sudo apt-get update

install:
  # Qt
  - sudo apt-get install libgl-dev qt511base qt511-meta-minimal qt511charts-no-lgpl qt511datavis3d-no-lgpl -y
  - source /opt/qt511/bin/qt511-env.sh

script:
  - eval "${MATRIX_EVAL}"
  - mkdir build
  - cd build
  - cmake "${COMPILER_FLAGS}" ${EXTRA_FLAGS} ..
  - make -j2 -k
  - cd ..
  - ${AFTER_BUILD}
